### ISSUE TITLE
alsa error

### ISSUE THREAD

**Issue by terrarier2111** [RustAudio/cpal#829] opened 2024-02-04 23:24 UTC
called `Result::unwrap()` on an `Err` value: BackendSpecific { err: BackendSpecificError { description: "ALSA function 'snd_pcm_open' failed with error 'EOPNOTSUPP: Operation not supported on transport endpoint'" } }

**Comment by Beinsezii** [comment] 2024-02-06 21:30
Is that with pipewire 1.0.2? That version has broken alsa interop.

**Comment by infamous-711** [comment] 2024-02-08 04:58
Just as @Beinsezii suggested, the error was caused by pipewire version 1.0.2. I also faced this error and after updating pipewire to 1.0.3 this issue is resolved for me.

**Comment by terrarier2111** [comment] 2024-02-09 16:26
> Is that with pipewire 1.0.2? That version has broken alsa interop.

Are you talking about a crate version? If so: i do not use a dependency called "pipewire", i am just using "cpal = "0.15.2" for audio IO

**Comment by Beinsezii** [comment] 2024-02-09 17:52
> Are you talking about a crate version? If so: i do not use a dependency called "pipewire", i am just using "cpal = "0.15.2" for audio IO

No, your actual system's pipewire version. Some distros use pipewire by default now instead of pulseaudio.

In the recent pipewire 1.0.2 version it looks for the wrong ALSA lib, so it's not able to play ALSA audio yet it still intercepts ALSA playback requests, reporting that the device has no output configurations.

Pipewire 1.0.3 has since been released, so try updating your system. Alternatively, try rolling back all the pipewire packages to 1.0.1

**Comment by Beinsezii** [comment] 2024-02-09 17:56
Upstream issue https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3830

**Comment by est31** [comment] 2024-02-10 12:58
Closing as it is not a cpal bug

**Closed by est31** 2024-02-10 12:58 UTC
