### ISSUE TITLE
Unable to build with asio feature

### ISSUE THREAD

**Issue by zomatree** [RustAudio/cpal#453] opened 2020-07-22 02:19 UTC
when trying to build with the `asio` feature it seems to fail as there is a conflict in the versions of clang that it wants
Cargo.toml
```toml
[package]
name = "client"
version = "0.1.0"
authors = ["Zomatree <39768508+zomatree@users.noreply.github.com>"]
edition = "2018"

[dependencies]
cpal = { git = "https://github.com/RustAudio/cpal", features = ["asio"] }
```

output:
```
PS C:\Users\Zoomatree\Documents\Coding\Rust\client> cargo build
    Updating git repository `https://github.com/RustAudio/cpal`
    Updating crates.io index
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.51.0`
    ... which is depended on by `asio-sys v0.1.0 (https://github.com/RustAudio/cpal#997fb9fa)`
    ... which is depended on by `cpal v0.12.0 (https://github.com/RustAudio/cpal#997fb9fa)`
    ... which is depended on by `client v0.1.0 (C:\Users\Zoomatree\Documents\Coding\Rust\client)`
versions that meet the requirements `^0.28.0` are: 0.28.1, 0.28.0

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v0.29.3`
    ... which is depended on by `bindgen v0.53.3`
    ... which is depended on by `coreaudio-sys v0.2.5`
    ... which is depended on by `coreaudio-rs v0.9.1`
    ... which is depended on by `cpal v0.12.0 (https://github.com/RustAudio/cpal#997fb9fa)`
    ... which is depended on by `client v0.1.0 (C:\Users\Zoomatree\Documents\Coding\Rust\client)`

failed to select a version for `clang-sys` which could resolve this conflict
```

**Comment by est31** [comment] 2020-07-22 04:25
Dupe of #450

**Comment by est31** [comment] 2020-07-22 04:28
Oh wait, no this is its own bug. Sorry about that!

This should be resolveable by updating the deps of asio-sys. Do you want to file a PR, @zomatree ?

**Comment by zomatree** [comment] 2020-07-22 04:57
i would PR it myself but i have no idea what im doing so it would be better if i didnt

**Comment by HEnquist** [comment] 2020-07-22 20:17
There is something strange going on here. This was from a build on windows, so why is coreaudio-rs and -sys being included?
Did you try doing a cargo clean?

**Comment by est31** [comment] 2020-07-22 21:23
Good catch. I'm not sure what's going on here. Anyways, it should be pretty easy to update bindgen in asio.

**Closed** 2020-07-22 21:36 UTC

**Comment by hyunh90** [comment] 2021-09-20 02:48
Hello,

Sorry for bumping closed issues, but I'm also experiencing this exact same symptom with cpal 0.13.4:
```toml
[package]
name = "audio-thingy"
version = "0.1.0"
edition = "2018"
publish = false

[dependencies]
cpal = { features = ["asio"], version = "0.13" } # Apache-2.0
log = "0.4" # MIT
```

```
**********************************************************************
** Visual Studio 2019 Developer Command Prompt v16.8.3
** Copyright (c) 2020 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'

V:\study\rust\audio-thingy>cargo build
error: failed to select a version for `clang-sys`.
    ... required by package `bindgen v0.54.0`
    ... which is depended on by `asio-sys v0.2.0`
    ... which is depended on by `cpal v0.13.4`
    ... which is depended on by `audio-thingy v0.1.0 (V:\study\rust\audio-thingy)`
versions that meet the requirements `^0.29` are: 0.29.3, 0.29.2, 0.29.1, 0.29.0

the package `clang-sys` links to the native library `clang`, but it conflicts with a previous package which links to `clang` as well:
package `clang-sys v1.2.2`
    ... which is depended on by `bindgen v0.56.0`
    ... which is depended on by `coreaudio-sys v0.2.8`
    ... which is depended on by `coreaudio-rs v0.10.0`
    ... which is depended on by `cpal v0.13.4`
    ... which is depended on by `audio-thingy v0.1.0 (V:\study\rust\audio-thingy)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='clang-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `clang-sys` which could resolve this conflict
```

**Comment by hyunh90** [comment] 2021-09-20 04:18
Realized there's an ongoing discussion at #383; will watch that instead.
