### ISSUE TITLE
Recent update panics, 'sample rate could not be set: "Invalid argument"'

### ISSUE THREAD

**Issue by jupart** [RustAudio/cpal#218] opened 2018-04-10 15:31 UTC
My project is https://github.com/jupart/skirm. I recently ran "cargo update" and everything builds fine, but I'm running into the panic on this line (even after a reboot):

cpal/src/alsa/mod.rs (line 788)
```
     check_errors(alsa::snd_pcm_hw_params_set_rate(pcm_handle,
                                                  hw_params.0,
                                                  format.sample_rate.0 as libc::c_uint,
                                                  0))
        .expect("sample rate could not be set");
```

**Comment by jupart** [comment] 2018-04-11 12:17
This may or may not be fixed already (I just saw your 0.8.1 changelog). `rodio` is using `cpal=0.6.0`.

**Comment by frazar** [comment] 2018-04-18 13:14
I think this is a duplicate of #173, where you can find a reason for this behavioiur.

I am myself in the same situation as you, and I've personally verified that the bug is not present in `cpal >= 0.8`.

I've already filed an [issue](https://github.com/tomaka/rodio/issues/160) on `rodio`'s page, and I'm trying to prepare a pull request to update their `cpal` dependency to 0.8.

**Comment by mitchmindtree** [comment] 2020-05-22 13:40
As this seems to be a dupe of #173 and that was reported fixed, I'm going to close this.

**Closed by mitchmindtree** 2020-05-22 13:40 UTC
Labels: bug
