### ISSUE TITLE
Stream dropped but audio callback still being called

### ISSUE THREAD

**Issue by morajabi** [RustAudio/cpal#771] opened 2023-04-03 21:53 UTC
I added a log where I drop the stream:
```
drop(stream);
info!("stream dropped");
```
and you can see I'm still getting samples from cpal:
![CleanShot 2023-04-04 at 01 21 58@2x](https://user-images.githubusercontent.com/12202757/229635576-97d34a01-1e4f-4bca-9b5d-2fd78548b6e6.png)

seems like after updating to 0.15 it appeared, let me downgrade and check.

**Update**: yes it doesn't happen in 0.14.

**Comment by est31** [comment] 2023-04-04 01:20
@morajabi would it be possible to do a git bisect? Then we know where to look.

**Comment by morajabi** [comment] 2023-04-04 10:11
@est31 I haven't used git bisect before and it seems like I need a focused commit on this change? My last commit contains other changes as well, I took out changes to our audio module that fixed the issue and these are that:
Cargo.toml
![CleanShot 2023-04-04 at 13 37 06](https://user-images.githubusercontent.com/12202757/229759688-1a30155a-c77a-43d1-a4cb-37389f507594.png)

build_input_stream
![CleanShot 2023-04-04 at 13 36 40](https://user-images.githubusercontent.com/12202757/229759718-2d21fe2a-506e-41a8-878d-826bf27037cb.png)

Sorry about posting screenshots — if it's still unclear I will try to create a reproduction repo later this week as I'm a bit busy atm.

**Comment by ZerNico** [comment] 2023-04-09 19:38
I can confirm, it happens in for me too on `0.15`, it doesn't happen on `0.14` or when using the default input device on `0.14`.

Here is a minimal reproduction.
```
use std::{time::Duration, thread};
use cpal::traits::{DeviceTrait, HostTrait, StreamTrait};

fn main() {
    let host = cpal::default_host();
    
    let mut input_devices = host.input_devices().expect("Failed to get input devices");
    let device = input_devices
    .next()
    .expect("Failed to get default input device");

    /*
    Works fine with this
    let device = host
        .default_input_device()
        .expect("Failed to get default input device");
    */

    let config: cpal::StreamConfig = device
        .default_input_config()
        .expect("Failed to get default input config")
        .into();

    let input_data_fn = move |data: &[f32], _: &cpal::InputCallbackInfo| {
        println!("data len: {}", data.len());
    };

    let input_stream = device
        .build_input_stream(&config, input_data_fn, err_fn, None)
        .expect("Failed to build input stream");

    input_stream.play().expect("Failed to play input stream");

    thread::sleep(Duration::from_secs(2));
    drop(input_stream);
    thread::sleep(Duration::from_secs(5));
}

fn err_fn(err: cpal::StreamError) {
    eprintln!("an error occurred on stream: {}", err);
}
```

**Comment by ZerNico** [comment] 2023-04-09 20:20
After some testing I found out that 0af6a1c is the commit that introduced the bug.

**Comment by cenzovit** [comment] 2023-10-13 00:04
Also running into this. Was extraordinarily confused by the callback still firing even when I had manually dropped the stream and ended the thread that was running my audio stream logic...

**Comment by Ralith** [comment] 2023-10-13 01:38
Is this macos-only?

**Comment by cenzovit** [comment] 2023-10-13 04:24
Not sure about other systems, but ran into the issue on macos as well.

**Comment by ZerNico** [comment] 2023-10-13 14:40
Could be only on MacOS. I only tried it there

**Comment by cenzovit** [comment] 2023-10-13 20:50
I am a little surprised more people haven't run into this issue since it seems it was introduced a year ago. I am torn because the bug is pretty bad, but the functionality the change was trying to introduce is important (triggering the error callback on device disconnect). 

In my use case, I need to resample the input stream to a specific sample rate. To do so, I need to know the sample rate of the input stream. This becomes an issue when the input stream magically switches devices / config without triggering any callbacks. This occurs when using the default device in cpal 0.15 and also seems to occur when using any device that disconnects in cpal 0.14. It would probably be more ideal if cpal also exposed an easy way to determine the device and config information from the input stream itself; however, having the callbacks trigger correctly is at least manageable.

**Comment by cenzovit** [comment] 2023-10-13 21:31
For this issue specifically, just from reading over the code, I am fairly certain the stream not closing is due to the cloning of the stream when setting the disconnect listener: https://github.com/RustAudio/cpal/blob/f51589c55261550407dc12dedd7a3e5512be77e1/src/host/coreaudio/macos/mod.rs#L456

**Closed** 2024-10-11 08:39 UTC
