### ISSUE TITLE
CPAL with ALSA backend not able to enumerate devices properly

### ISSUE THREAD

**Issue by svanharmelen** [RustAudio/cpal#357] opened 2020-01-05 19:31 UTC
When I (cross) compile the `enumerate` `CPAL` example and run it on the target device I get this list:

```
Supported hosts:
  [Alsa]
Available hosts:
  [Alsa]
ALSA
  Default Input Device:
    Some("default")
  Default Output Device:
    Some("default")
  Devices:
  1. "default:CARD=I2S"
  2. "sysdefault:CARD=I2S"
  3. "default:CARD=UAC20"
  4. "sysdefault:CARD=UAC20"
```

If I do the same, but then using the `devices` `rust-portaudio` example I get this list:

```
Number of devices = 5
Default input device: Ok(DeviceIndex(3))
Default output device: Ok(DeviceIndex(3))
All devices:
--------------------------------------- DeviceIndex(0)
DeviceInfo {
    struct_version: 2,
    name: "MTK APSoC I2S: - (hw:0,0)",
    host_api: 0,
}
--------------------------------------- DeviceIndex(1)
DeviceInfo {
    struct_version: 2,
    name: "ReSpeaker MicArray UAC2.0: USB Audio (hw:1,0)",
    host_api: 0,
}
--------------------------------------- DeviceIndex(2)
DeviceInfo {
    struct_version: 2,
    name: "sysdefault",
    host_api: 0,
}
--------------------------------------- DeviceIndex(3)
DeviceInfo {
    struct_version: 2,
    name: "default",
    host_api: 0,
}
--------------------------------------- DeviceIndex(4)
DeviceInfo {
    struct_version: 2,
    name: "dmix",
    host_api: 0,
}
```

_Stripped some output to make the lists easier to read_

As you can see, I get one device less using `CPAL` (4 vs 5) and I get strange (and partly duplicate) names instead of the much nicer and clearer names `rust-portaudio` returns.

Is this something that is expected and/or can I tweak something to improve/fix this? Thanks!

**Comment by sniperrifle2004** [comment] 2020-06-22 12:41
Well what cpal is doing is listing alsa hints about devices. Depending on the precise alsa configuration a device like `dmix` will not show up, while it does still exist. The devices `(sys)default:<card>` represent the default configuration of that card if it is slaved to the `(sys)default` pcm (Again this is something that varies and can also be affected by environment variables). Looks like your configuration is also hiding the "default" and "sysdefault" hints. I have seen other configurations that seem to do this, but haven't been able to reproduce that myself.

Now what I suspect `port-audio` might be doing, is first listing cards and their devices and generating device information (probably using `hw:(0,0)` like names to open the pcm's when using those) from that and after that adding some other alsa pcm's (Whether or not it actually also lists all hints first I don't know).

**Comment by svanharmelen** [comment] 2020-06-22 15:28
Check... Well I'm fine with closing this one as this is no longer something I'm working on. So unless you want to keep it open for reference, shall I close it?

**Comment by sniperrifle2004** [comment] 2020-06-22 15:38
I'm fine with closing it. I can reference to the information in it even if it's closed so that's fine. I also believe that listing devices based on hints is the correct approach, though admittedly having more friendly names to display would be nice.

**Closed** 2020-06-22 15:40 UTC
Labels: host - alsa, platform - linux
