### ISSUE TITLE
Getting rid of the EventLoop

### ISSUE THREAD

**Issue by ishitatsuyuki** [RustAudio/cpal#278] opened 2019-06-06 10:16 UTC
More and more platforms are running audio with synchronous callback in a high-priority thread. That means that thread management should happen inside cpal, not in user code.

The blocking design of `EventLoop` should be replaced by some interface of registering callback. What's unfortunate is that we would need not only `Send` but also the `'static` bound on the callback if it's implemented naively. Do we have anything more Rust-ic than callbacks (which is C-ish and often messy)?

It's obvious that we need different callbacks for different `Host`s (assuming it get implemented), but should we support driving multiple streams with the same callback?

**Comment by mitchmindtree** [comment] 2019-06-06 13:03
Ahh this reminds me that, if we are to get rid of the `EventLoop`, we're going to have to spawn a thread internally for platforms that don't automatically use a separate, high-priority thread.

E.g. the current ALSA implementation is just a big synchronous loop that blocks on file descriptors and at a quick glance the WASAPI implementation of `run` also looks quite similar. I believe this was the original rational for the `EventLoop` - to provide a consistent blocking API so that the behaviour is the same across all platforms regardless of whether or not the platform calls the callback given to `run` on a separate thread or not.

I'm not sure I feel comfortable with CPAL spawning an entire thread within the wasapi and alsa implementations just to allow for non-blocking API consistency. Right now, the user can gain a *kind* of consistent, non-blocking API by calling `fn run` on a separate thread. While this is annoying for coreaudio users, the alternative approach (of spawning a thread within the wasapi and alsa backends in order to remove the blocking EventLoop) is equally inconvenient to wasapi and alsa users. There are also many different ways to spawn a thread, and I imagine it might be difficult for CPAL to do this in a way that is optimal for all users.

Also, before doing something like this it would likely be worth considering how web support will look. I haven't looked at that API yet, but I imagine it will be important to consider as I'm aware just "spawning a thread" in web APIs is not a simple task.  Hopefully someone with some more knowledge on this can comment.

I do agree that the current situation with the blocking `EventLoop` is not great, but after giving it some thought I'm not convinced that removing the `EventLoop` won't just move the current issues to somewhere else...

## EventLoop Issues

Perhaps it is first worth outlining the specific issues that currently exist with the `EventLoop`:

- In attempting to provide a unified blocking API, it requires users of platforms that only offer non-blocking (high-priority) APIs to spawn one extra thread than they should otherwise have to.
- The `EventLoop::run` method never returns. The current, never-ending `fn run` signature makes cleaning up the audio thread cleanly an impossible task. Perhaps investigating this and seeing if we can come up with some API that allows for returning from the call in a nice manner might at least improve the current situation slightly?
- Seeing as the vast majority of use-cases for audio require that the audio processing does not block the main thread, users normally require spawning their own thread. While it makes sense for users to make the choice on how they do this (e.g. as a part of a tokio runtime, or via `std::thread`, or via some other more configurable threading approach), it creates other implications for the `EventLoop` API. In almost all cases, we require wrapping the `EventLoop` in an `Arc` so that we may still play, pause, create and destroy streams at run-time. Platform implementations need to be aware of this and ensure these methods are thread-safe while also ensuring that `EventLoop` implements `Sync` - a non-trivial task in unsafe, FFI heavy code.

What are your thoughts on all this @ishitatsuyuki ?

**Comment by mitchmindtree** [comment] 2019-06-06 13:09
> Do we have anything more Rust-ic than callbacks (which is C-ish and often messy)?

While I agree callbacks do not feel very naturally Rusty, unfortunately it's often the only way to provide consistent behaviour across multiple backends in a zero-cost manner that doesn't make decisions related to synchronisation and threading for the user. In some cases (like when supporting web APIs) it's downright impossible to avoid... This is a realisation that the [winit](https://github.com/rust-windowing/winit) developers have come to recently and from my understanding is one of the main motivating factors behind the winit "event loop 2.0" re-write.

**Comment by ishitatsuyuki** [comment] 2019-06-06 13:29
> we're going to have to spawn a thread internally for platforms that don't automatically use a separate, high-priority thread.

Even if the API doesn't force you to do so, there's often a (separate) way to get a high priority thread. It doesn't harm to do so as long as it's available. Examples are multimedia work queue on Windows, RtKit on Linux.

> ... is equally inconvenient to wasapi and alsa users.

Are you trying to say that you (or "WASAPI/ALSA users") have a preference on blocking API?

One of the goals with the proposed non-blocking APIs is that we handle thread spawning and therefore do it in the best way on each platform.

> Also, before doing something like this it would likely be worth considering how web support will look

I briefly investigated this, isn't the non-blocking API better for web usages? After all, you're not supposed to take over the "main thread", which doesn't actually block. It should be up to the user to call `stdweb::event_loop`.

And on to EventLoop issues...

1. the "redundant thread" problem is probably just another way around with non-blocking API, but that's a matter of preference as long as we only provide one of the paradigm.
2. stopping the non-blocking event loop can happen via either explicit `stop` API call or just dropping.
3. the synchronization problem holds, however it's not performance critical as stream operations are rarely performed. If handling in each backend is infeasible, we may just use a Mutex in the shared part.

Re: callbacks, the case study of winit was interesting. On making it more rusty - maybe we can use a trait instead of `FnMut`, given that user code dealing with audio is unlikely to fit in one closure.

**Comment by mitchmindtree** [comment] 2019-06-06 15:20
> there's often a (separate) way to get a high priority thread. It doesn't harm to do so as long as it's available. Examples are multimedia work queue on Windows, RtKit on Linux.

Ahh I'm unfamiliar with both of these APIs. Would this involve abandoning the WASAPI and ALSA hosts altogether? Or do these APIs work nicely alongside the WASAPI and ALSA?

> Are you trying to say that you (or "WASAPI/ALSA users") have a preference on blocking API?

I don't at all prefer the blocking API and I'd imagine most users would prefer a dedicated high-priority thread if it's available, but from my understanding these options are not always available, (e.g. on low-powered devices, or APIs like ALSA). I could be totally wrong about this and I hope that I am! What I meant by "equally inconvenient" is that I'm concerned that by only providing a non-blocking API, we are simply moving the burden from the natively non-blocking hosts to the natively blocking hosts.

Just for reference, [PortAudio decided to add an additional blocking API](http://www.portaudio.com/docs/proposals/005-BlockingReadWriteInterface.html) back in 2001 as a result of repeated user-request. Unfortunately, some of the threads discussing earlier motivation are dead links. It's possible that the motivations behind this in 2001 are no longer prevalent today, but I think it's important to be aware of how other APIs are dealing with this. It might be interesting to investigate how other cross-platform APIs like libsoundio or JACK are approaching this, and whether or not they even provide a blocking API.

Sorry for adding confusion! Ultimately, I'd prefer to only provide a non-blocking API if is possible to do so. I just want to be careful that we are not excluding users that have different needs without realising it.

**Comment by ishitatsuyuki** [comment] 2019-06-07 03:34
> Ahh I'm unfamiliar with both of these APIs. Would this involve abandoning the WASAPI and ALSA hosts altogether? Or do these APIs work nicely alongside the WASAPI and ALSA?

Yeah, they work just fine. They are just separate APIs to raise thread priority, to say in short.

On blocking API - I think you're confusing the relationship with push and pull based modes. (In the following description, I would refer to output stream as it's a way around with input streams.) The current `EventLoop` design blocks the user's thread, but is still pull based. In the case of PortAudio the users wanted push-based APIs.

To compare the two, pull-based API excels at lowering latency, while push-based API relies less on precise scheduling. The latter is better for e.g. music playing applications, where power saving is a goal.

We probably should expose both - with some caveats on Linux though, as ALSA (and PulseAudio) is push-only and JACK is pull-only. [PipeWire](https://fosdem.org/2019/schedule/event/pipewire/attachments/slides/2826/export/events/attachments/pipewire/slides/2826/PipeWire.pdf) is ultimately going to solve both, anyway.

Back to the topic, getting rid of the EventLoop is what we should do now, because that isn't what users of push-based API want anyway. We could implement push-based API in the future.

**Comment by mitchmindtree** [comment] 2019-06-07 11:54
> On blocking API - I think you're confusing the relationship with push and pull based modes. (In the following description, I would refer to output stream as it's a way around with input streams.) The current EventLoop design blocks the user's thread, but is still pull based. In the case of PortAudio the users wanted push-based APIs.

Thanks for the concern, but I'm not confused about blocking and push-based APIs. I'm well aware CPAL's current approach is pull-based blocking while the approach PortAudio went with is push-based blocking, and I'm aware of the impact both have on performance. My actual concern is exactly as I stated, *I just want to be careful that we are not excluding users that have different needs without realising it.* If you're convinced that we can use multimedia work queue with WASAPI on windows and RtKit with ALSA on Linux without excluding certain windows or linux systems and their users, then I am satisfied and happy to see this go ahead.

**Comment by mitchmindtree** [comment] 2019-06-07 18:50
I think the issue raised by [this comment](https://github.com/tomaka/cpal/issues/245#issuecomment-437141514) might be worth investigating / keeping in mind before diving into this.

**Comment by ishitatsuyuki** [comment] 2019-06-08 08:46
> If you're convinced that we can use multimedia work queue with WASAPI on windows and RtKit with ALSA on Linux without excluding certain windows or linux systems and their users, then I am satisfied and happy to see this go ahead.

RtKit is installed in most desktop installations, similar to how widespread PulseAudio is. On systems without it, we can surely gracefully fallback to a normal thread, so this wouldn't cause any harm for *users*. There could be cases where developers want their own way to spawn thread, but whether it's in the scope... I'll leave it up to you.

Regarding the WASM issue - I think removing EventLoop actually address it. Am I missing something? If so, would you mind explaining in detail?

**Comment by BartMassey** [comment] 2019-06-11 08:06
> Just for reference, [PortAudio decided to add an additional blocking API](http://www.portaudio.com/docs/proposals/005-BlockingReadWriteInterface.html) back in 2001 as a result of repeated user-request. Unfortunately, some of the threads discussing earlier motivation are dead links. It's possible that the motivations behind this in 2001 are no longer prevalent today, but I think it's important to be aware of how other APIs are dealing with this. 

I'm here because the `rust-portaudio` blocking API implementation is buggy and [doesn't work](https://github.com/RustAudio/rust-portaudio/issues/119#issuecomment-500712121).

Sadly, I'm leaving here because `cpal` currently provides no way for my program to stop and clean up my audio stream when the audio is finished playing, as far as I can tell.

I'm not sure where my next stop is. I'd really love a cross-platform API that just gave me simple blocking calls to read and write audio with no callbacks involved, letting me create my own threads as needed to do async audio. Bonus points if I got a cross-platform way to fork a high-priority thread for the audio to run on. Extra bonus points if things worked with WASM and WebAudio.

**Comment by ishitatsuyuki** [comment] 2019-06-11 12:49
@BartMassey What's your reason for using blocking API? In general callback based APIs are preferred because latency is more predictable, plus that it's a more direct way to communicate with the OS. (This makes it a must-have for small buffer sizes.)

The rest of the problems are already discussed and is something we will tackle.

**Comment by BartMassey** [comment] 2019-06-11 21:08
Right now I'm trying to write audio pulled from a thing that's not `Send`, so I don't see how to move it into the callback. Maybe my Rust skills are just insufficient. <https://github.com/pdx-cs-sound/synthkit/tree/cpal-send> at `src/play.rs` has my current code.

Other than that I'm not wedded to the blocking API. I do need to be able to close the audio stream when I'm done playing. Adding a return value to the callback that indicates the disposition of the stream like `rust-portaudio` does would be a fine solution for that I think.

I'm not super-worried about latency with the blocking approach: I'm writing 16 samples at a time in a tight loop: I think that's about as good as a normal-people audio card is going to do latency-wise. I've currently moved to [`portaudio-rs`](http://github.com/mvdnes/portaudio-rs), which seems to keep up fine with a pure-blocking interface so far.

**Comment by ishitatsuyuki** [comment] 2019-06-13 04:45
@BartMassey You said "that's not `Send`" - does that mean that you have something that really isn't `Send` or it was just a problem with trait bounds? I modified your code a bit and it compiles: https://github.com/ishitatsuyuki/synthkit/commit/623901f9059bcd80c9335821f88a31eaa3b23ba4. Let me know if that was what you needed.

**Comment by ishitatsuyuki** [comment] 2019-06-13 07:36
Here are some additional thoughts.

Based on how Android's AAudio is implemented, I believe we should use a dedicated callback per stream as it's how the downstream API is designed.

Additionally, I wonder if we should expose the play/pause actions to the processing thread only? Those actions are already implemented using channels or mutexes on virtually every backend, and we can go a level down by not doing additional synchronizations. However, apart from synchronizations they also contains an implementation to wake up the processing thread, which we will have to expose to the user if we restrict the play/pause actions to the processing thread.

**Comment by mitchmindtree** [comment] 2019-06-13 10:13
> Based on how Android's AAudio is implemented, I believe we should use a dedicated callback per stream as it's how the downstream API is designed.

Agreed! macos also works like this, and I don't imagine it would be too tricky setting this up for WASAPI and ALSA. It would also mean we can avoid having to lock the callback (currently required as multiple different audio devices need access to the one user callback).

> Additionally, I wonder if we should expose the play/pause actions to the processing thread only?

I think I could go either way on this. macos provides a non-blocking, user-thread API for this (but their whole API is non-blocking so no surprise here). ALSA on the other hand requires this to be done on the processing thread I believe. I don't quite remember what the case is for Windows. Do you know how this is handled on Android?

**Comment by ishitatsuyuki** [comment] 2019-06-13 13:33
> I don't quite remember what the case is for Windows. Do you know how this is handled on Android?

For Windows the documentation is not very clear; but probably stream operations should be done on the same thread as stream creation (the doc mentions STA in COM but it's unclear what functions it applies to).

For Android, 1. the library does not perform synchronization and 2. you cannot perform stream operations from either data or error callback.

So well... maybe we can make all the APIs take `&mut` or just do the synchronization in the backends.

**Comment by BartMassey** [comment] 2019-06-13 21:19
@ishitatsuyuki Thanks much for pointing out that I was being the dumbz about the trait bounds! I didn't think through that it would be `Safe` to send all of the iterators I am using / building.

It would still be great if there was a way for the callback to indicate that it is finished playing the stream so it could get unregistered. That would be the icing on the cake for me.

**Comment by ishitatsuyuki** [comment] 2019-07-06 11:21
Started working on this. Will open a PR after finishing on ALSA backend.

**Comment by derekdreery** [comment] 2019-08-04 10:57
> Regarding the WASM issue - I think removing EventLoop actually address it. Am I missing something? If so, would you mind explaining in detail?

Yes I'm currently experimenting with implementing cpal in wasm32-unknown-unknown using wasm-bindgen/web-sys, but I'm stuck because of the `run` function signature - I want to just schedule a callback to run every so often using `setTimeout`, i.e. it has to be non-blocking.

**Comment by MOZGIII** [comment] 2019-08-29 01:30
How about we try to expose *some* internals of the host implementations to the user? Don't get me wrong - I don't have anything against providing a unified API where it can be done naturally. Sometimes, however, it's just not possible, while simultaneously providing a low-overhead solution.

What I propose is to *somehow* allow every `Host` to have it's own way of startup mechanism. It makes total sense to expose and give user control over the fact that for some Host implementations there has to be an even loop running, and for some others all you need is to *just* expose the callbacks. Given that we expose those details - we can also provide an adapter with a single interface that would bring-up all the lower-level implementations (dynamic dispatch style or generic over the underlying Host implementation). That way we can both expose the control over low level execution details for people that care about them, and also allow for a simpler to use interface for the ones that don't want to tweak how the audio engine threading works and other low-level details.

This is nothing concrete, but before trying to work something out - how do you guys feel about this idea of exposing more internals to provide better control?

**Comment by MOZGIII** [comment] 2019-08-29 01:33
My concrete issue and the reason why I'm proposing the above is summarized in that I'm not a big fan of cpal spawning thread behind the scene for ALSA host.

**Comment by est31** [comment] 2019-08-29 01:39
When winit did their event loop 2.0 refactor, they made the main way as portable as possible and have added [extensions](https://docs.rs/winit/0.20.0-alpha3/winit/platform/desktop/trait.EventLoopExtDesktop.html) for platforms that support it.

Ultimately, the goal of cpal/winit is to abstract over operating system APIs so the default being the least common denominator is I think the best solution here. I'm not sure how well extension traits could be realized for cpal, but if a solution isn't imposing too large restrictions on internal code, I'm all for it.

**Comment by ishitatsuyuki** [comment] 2019-08-29 01:45
My vision for cpal is portability first too. If there's something we want to (that is useful to) achieve but it isn't portable, then we expose platform-specific APIs. (I don't plan to do extensions but only `Host` specific methods - each platform usually has its caveat and I prefer the user being explicit to handle them.)

And therefore I don't see your point @MOZGIII. Spawning a new thread is perfectly fine, because threads are cheap when seen as one-time cost. On the other hand, dividing the cpal API into two is just disastrous and it makes maintenance much harder.

**Comment by MOZGIII** [comment] 2019-08-29 02:31
Maybe there's no issue with just spawning a thread, since I already have to do it with the existing API just to be able to anything else, since current API is blocking. However, what could be a problem is a lack of control over how the thread is spawned. I understand that it makes most sense to focus on the most common use cases, and simply not support anything exotic that requires lower-level control. The problem is it's just not much other thing the rust ecosystem currently offers in term of crates besides a bunch of `*-sys` bindings, that aren't safe. That said, probably power users would be willing to go that route either way for the extra degree of control. I don't know. Seems like the case I'm presenting is not that strong - that's most likely because I don't have the concrete cases for it though (and not because it's not worth supporting - it's not the common one but still).

I fully understand your concerns about the API surface growth @ishitatsuyuki. As a user of cpal and as an maintainer of a number of software projects - I'm fully aware how important the API is, I too have a lot of concern for keeping it simple. Yet after considering all pros and cons, I don't think we should be afraid for the API that much that we just give up on this topic. After all, from my practice, instead of exposing lower-level details as is, it just so happens usually that another set of useful abstractions is uncovered, allowing for both low-level control and elegant common use case, along with easier to reason about architecture design. The expected outcome for my perspective would be  another layer of indirection in some form, well defined and easy for both users and maintainers (i.e. like the new `Host` abstraction that was just added recently). I'm not seeing the goal to divide the API or anything.

I do not exclude that the solution to the event loop problem that you have in mind might already have all those properties, or it be a step forward for us to see the proper abstractions we need to extract to move further in plain sight.

So I'm all for the currently planned changes, but I'm still thinking that maybe we can do even better.

**Comment by MOZGIII** [comment] 2019-08-29 02:43
@est31 speaking of the least common denominator - that's true, but there's a catch - what if there no common denominator across all the systems? In essence - what do we do if some system requires user to provide "execution medium" (i.e. a thread) while other requires user to operate with just callbacks, while system provides the execution medium and manages the control flow? I mean, to me it looks like those cases are mutually incompatible over who provides the execution medium. Of course it's ultimately the third party to both cpal and the user code that manages both the execution mediums (i.e. kernel manages threads) and audio hardware in the modern systems (unless we do kernel development and/or audio engine like pulse audio) - so for this particular case, maybe we can assume that the common denominator would be that `cpal` takes care of the execution medium, whatever's needed. That's just not very low level to me, cause I'm convinced we can go even lower level without compromising on the API or maintainability. The only problem is the solution is not obvious yet.

**Comment by MOZGIII** [comment] 2019-08-29 02:45
Heck, I believe in magic in software, I admit it. 😄

**Comment by mitchmindtree** [comment] 2020-01-14 19:32
Closed by #354

**Closed by mitchmindtree** 2020-01-14 19:32 UTC

**Comment by voidshine** [comment] 2020-03-30 01:25
Callbacks are fine and fast. All the event loop needs is a way to break out. A return value, a method to call... there are a few convenient ways to do it. In my opinion, cpal should not be starting up its own thread because that would be making architecture decisions better left to the application. I like cpal as a simple low-level library, and leaving concurrency concerns in the app developer's hands will make it a better fit for more apps.

**Comment by ishitatsuyuki** [comment] 2020-03-31 01:06
What kind of architecture decisions are you talking about? The new API was introduced partly due to inefficient wrapping of managed callbacks in previous API (e.g. macOS CoreAudio is designed that way).

In the old way cpal wasn't a "simple" low-level library in any sense. The current API is what is effectively mandatory way to do low-latency audio. For less latency-intensive usecase, I guess this might not be the easiest, but it's more like middleware's job to wrap it nicely (for example, rodio).

**Comment by voidshine** [comment] 2020-03-31 04:13
Specifically, I am referring to concurrency architecture. The decisions
about whether to spawn a thread, exactly how that gets done, etc., should
be left up to the application, not cpal. All I want from cpal is a way to
break out from the event loop, and a return value is sufficient to do so
efficiently. There are other ways, but in my opinion spawning threads
shouldn't even be considered. I'm only speaking up here because I like cpal
and want to continue using it as a low-level audio API. Thanks for all your
hard work on this, by the way!
